site_name: "Pandas Tools"

theme:
  name: "material"
  language: en
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: 'getting_started/quickstart.md'
  - Abc:
    - abstracts: 'abc/abstracts.md'
  - Core:
    - dataframe: 'core/dataframe.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - mkdocstrings